databases:
  - name: swirl_backenddb
    plan: free
    databaseName: swirl_backend
    user: swirl_backend

services:
  - type: web
    plan: free
    name: swirl-backend
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: swirl_backenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4