databases:
  - name: swirl-backenddb
    plan: free
    databaseName: swirl-backend
    user: swirl-backend

services:
  - type: web
    plan: free
    name: swirl-backend
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn swirl-backend.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: swirl-backenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4